### ISSUE TITLE
Add support for OData

### ISSUE THREAD

**Issue by aidancasey** [greyham/Moksy#2]
It would be neat if Moksy let you pattern match a URL with an oData qyery like the following, round brackets aren't being matched ATM...

 http://services.odata.org/V4/TripPinServiceRW/People('russellwhyte')

**Comment by greyham** [comment]
Sounds like a good idea. I can see a few different scenarios here - so can I please ask which would satisfy your immediate problem? Are you: (in order of implementation difficulty):

1. Looking to match the URL explicitly against patterns that happen to resemble OData? ie: GET ../People('GreyHam'). In this case, we can probably take OData out of the equation and just modify the monstrous RouteParser.RegularExpression to support brackets and so forth. 
2. Looking to match the URL explicitly against a more complex OData expression (ie: such as a query with $filter and so forth?) like the example identified here: https://msdn.microsoft.com/en-us/library/hh169248(v=nav.80).aspx. This would not really apply the OData filter prior to the objects being returned but would support better matching on the URL. 
3. (2) with the OData filter being supported within Moksy so that the returned object was fully filtered by OData. 

Cheers!
